#Original Image Shape
ORG_IMAGE_HEIGHT = 160
ORG_IMAGE_WIDTH = 320
ORG_IMAGE_CHANNEL = 3

CORP_IMAGE_HEIGHT = 80
CORP_IMAGE_WIDTH = 160


CORP_IMAGE_HEIGHT2 = 64
CORP_IMAGE_WIDTH2 = 64


#File Path
DRIVE_LOG_FILE = 'data/driving_log.csv'
DATA_FILE_PATH = 'data/IMG/'